### ISSUE TITLE
beta function with a glm model including offset leads to error 

### ISSUE THREAD

**Issue by mellorjc** [jeff-hughes/reghelper#15]
The example script

```R
library(reghelper)

N <- 1000
data <- data.frame(x=rnorm(N),
                   y=rbinom(N, 2, 0.2),
                   z=runif(N))
orig.model <- glm('y ~ offset(log(z)) + x', family='poisson', data=data)
model <- beta(orig.model, skip=list(a='offset(log(z))'))

```

leads to the output:

```
Attaching package: ‘reghelper’

The following object is masked from ‘package:base’:

    beta

Error in offset(log(z)) : object 'z' not found
```

**Comment by jeff-hughes** [comment]
Thanks for flagging this. I've identified the issue and a potential solution. Essentially, fitted glm models store the data in two places: one is the raw data (`orig.model$data`), and the other is more specifically just the data involved in the model, and after calculating transformations (`orig.model$model`). This is a little different from how it works with lm models (which only have `model` and not `data`), so your example ends up being an edge case where the distinction between the two matters.

Anyway, I can push a fix for it soon, I just need to spend a bit more time testing to make sure that there are no unintended consequences that result from switching to using `orig.model$data`.
